edition: 1.0.0 #  命令行YAML规范版本，遵循语义化版本（Semantic Versioning）规范
name: fc-sdtest
access: default
vars:
  region: "cn-hangzhou" 
  serviceName: "serverless-sdtest"
  functionName: "sdtest" 
  # imageUrl: "registry.cn-hangzhou.aliyuncs.com/aliyun-fc/fc-stable-diffusion:anime-v12" 
  imageUrl: "registry.cn-hangzhou.aliyuncs.com/pdkpdk/sdcppdeploy:1"
  enableCollect: ""
  service:
    name: "serverless-sdtest"
    description: 'sdtest 部署到函数计算'
    internetAccess: true
    nasConfig: auto

services:
  sdtest:
    component: fc
    actions: 
      post-deploy: 
        - component: fc ondemand put --qualifier LATEST --max 1
    props:
      region: ${vars.region}
      service: ${vars.service}
      function:
        name: ${vars.functionName}
        description: sdtest函数
        handler: index.handler
        timeout: 600
        diskSize: 1024
        caPort: 9999
        instanceType: fc.gpu.tesla.1
        runtime: custom-container
        cpu: 8
        customContainerConfig:
          args: ''
          accelerationType: Default
          image: ${vars.imageUrl}
          accelerationInfo:
            status: Preparing
          command: ''
          webServerMode: true
        instanceConcurrency: 100
        memorySize: 32768
        gpuMemorySize: 16384
        asyncConfiguration: {}
        environmentVariables:
          EXTRA_ARGS: ${vars.extraArgs}
          ENABLE_COLLECT: ${vars.enableCollect}
      triggers:
        - name: defaultTrigger
          description: ''
          type: http
          qualifier: LATEST
          config:
            methods:
              - GET
              - POST
              - PUT
              - DELETE
            authType: anonymous
            disableURLInternet: false
      customDomains:
        - domainName: auto
          protocol: HTTP
          routeConfigs:
            - path: /*
